apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    cluster: application
    component: monitoring
    service: metrics-collector
  name: metrics-collector
  namespace: __NPH_NAMESPACE
spec:
  endpoints:
  - interval: 60s
    port: metrics
  jobLabel: component
  selector:
    matchLabels:
      service: metrics-collector
