[[constraint]]
  name="github.com/rs/zerolog"
  version="v1.8.0"

[[constraint]]
  name="github.com/spf13/cobra"
  version="v0.0.3"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.18.0"

[[constraint]]
  name = "github.com/nalej/derrors"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/nalej/grpc-infrastructure-go"
  version = "v0.0.32"

[[constraint]]
  name = "k8s.io/client-go"
  version = "^v8.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.7"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.7"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[constraint]]
  name = "github.com/nalej/grpc-infrastructure-monitor-go"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/nalej/grpc-app-cluster-api-go"
  version = "v0.0.14"
