kind: Service
apiVersion: v1
metadata:
  name: components-lister
  namespace: __NPH_NAMESPACE
  labels:
    component: monitoring
    service: components-lister
spec:
  selector:
      component: monitoring
      service: components-lister
  type: ClusterIP
  clusterIP: None
  ports:
  - name: deployments
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: daemonsets
    protocol: TCP
    port: 9001
    targetPort: 9001
  - name: statefulsets
    protocol: TCP
    port: 9002
    targetPort: 9002
