apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: monitoring
    service: components-lister
  name: components-lister
  namespace: __NPH_NAMESPACE
spec:
  endpoints:
  - interval: 60s
    port: deployments
  - interval: 60s
    port: daemonsets
  - interval: 60s
    port: statefulsets
  jobLabel: service
  selector:
    matchLabels:
      component: monitoring
      service: components-lister
