kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: application
    component: monitoring
    service: components-lister
  name: components-list
  namespace: __NPH_NAMESPACE
data:
  deployments: |
    app-cluster-api
    deployment-manager
    device-controller
    elastic
    kube-state-metrics
    metrics-collector
    musician
    prometheus-operator
    unified-logging-slave
  daemonsets: |
    filebeat
    node-exporter
  statefulsets: |
    prometheus-k8s
