kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: infrastructure-monitor
    service: infrastructure-monitor-coord
  name: infrastructure-monitor-coord
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: management
      component: infrastructure-monitor
      service: infrastructure-monitor-coord
  template:
    metadata:
      labels:
        cluster: management
        component: infrastructure-monitor
        service: infrastructure-monitor-coord
    spec:
      containers:
      - name: infrastructure-monitor-coord
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/infrastructure-monitor-coord:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: management-config
                key: environment
        args:
        - "run"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--caCert=/nalej/$(ENVIRONMENT).pem"
        - "--debug"
        ports:
        - name: api-port
          containerPort: 8423
      imagePullSecrets:
      - name: nalej-registry
