{
 "title": "{{.ClusterName}}",
 "description": "{{.ClusterName}}",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node readiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:kube_node_status_condition:selectready{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node disk pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:kube_node_status_condition:selectdiskpressure{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Component readiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deployment:kube_deployment_status_replicas_available_per_spec:union_ratio{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "daemonset:kube_daemonset_status_number_available_per_desired:union_ratio{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{daemonset}}"
    },
    {
     "expr": "statefulset:kube_statefulset_status_replicas_ready:union_ratio{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Node memory pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node:kube_node_status_condition:selectmemorypressure{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_used_seconds:avg_rate{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_MemUsed_bytes:sum{cluster_id=\"{{.ClusterId}}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}