apiVersion: v1
kind: Service
metadata:
  labels:
    component: monitoring
    service: kube-state-metrics
  name: kube-state-metrics
  namespace: __NPH_NAMESPACE
spec:
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https-main
  selector:
    component: monitoring
    service: kube-state-metrics
