apiVersion: v1
kind: Service
metadata:
  labels:
    component: monitoring
    service: node-exporter
  name: node-exporter
  namespace: __NPH_NAMESPACE
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9101
    targetPort: https
  selector:
    component: monitoring
    service: node-exporter
