apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-config
  namespace: __NPH_NAMESPACE
  labels:
    component: monitoring
    service: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
