apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
# For each namespace where there are services to be monitored
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: __NPH_NAMESPACE
    labels:
      component: monitoring
      service: prometheus
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: __NPH_NAMESPACE
