apiVersion: rbac.authorization.k8s.io/v1
kind: RoleList
# For each namespace where there are services to be monitored
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-k8s
    namespace: __NPH_NAMESPACE
    labels:
      component: monitoring
      service: prometheus
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
