kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: monitoring
    service: monitoring-manager
  name: monitoring-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: management
      component: monitoring
      service: monitoring-manager
  template:
    metadata:
      labels:
        cluster: management
        component: monitoring
        service: monitoring-manager
    spec:
      containers:
      - name: monitoring-manager
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/monitoring-manager:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: management-config
                key: environment
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--edgeInventoryProxyAddress=edge-inventory-proxy.nalej:5544"
        - "--caCertPath=/nalej/ca-certificate/ca.crt"
        - "--clientCertPath=/nalej/tls-client-certificate/tls.crt"
        - "--skipServerCertValidation=false"
        - "--useTLS=true"
        ports:
        - name: api-port
          containerPort: 8423
        volumeMounts:
          - name: ca-certificate-volume
            readOnly: true
            mountPath: /nalej/ca-certificate
          - name: tls-client-certificate-volume
            readOnly: true
            mountPath: /nalej/tls-client-certificate
      imagePullSecrets:
      - name: nalej-registry
      volumes:
        - name: ca-certificate-volume
          secret:
            secretName: ca-certificate
        - name: tls-client-certificate-volume
          secret:
            secretName: tls-client-certificate
