kind: Service
apiVersion: v1
metadata:
  name: monitoring-manager
  namespace: __NPH_NAMESPACE
  labels:
    cluster: management
    component: monitoring
    service: monitoring-manager
spec:
  selector:
      cluster: management
      component: monitoring
      service: monitoring-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8423
    targetPort: 8423
